### ISSUE TITLE
Combined D3.2.2 & D3.2.3

### ISSUE THREAD

**Issue by berndresch** [ZGIS/malawi_atlas_public#27]
Task description according to DoW:
- Integration of data from 2-3 external web services (possibly include health services, but have a ‘soft’ maximum of about 4 services)
- Other data updates and support, training COOPI staff on web portal

**Comment by JakobMiksch** [comment]
three layers have been added:
- `Accumulated Precipitation" 
- `Risk of Drought Impact for Agriculture`
- `Disaster Alerts - GDACS`

This was also part of the workshop.

See also: 
https://github.com/ZGIS/malawi_atlas_public/blob/master/webapp/resources/config/config.json#L3005-L3030
