### ISSUE TITLE
Download data in more formats

### ISSUE THREAD

**Issue by JakobMiksch** [ZGIS/malawi_atlas_public#4]
targeted to people who do not have a geo background e.g. CSV

**Comment by grmpfhmbl** [comment]
GeoServer should be able to do this when providing the correct parameters to WFS/WMS.

See
https://docs.geoserver.org/latest/en/user/services/wfs/outputformats.html https://docs.geoserver.org/latest/en/user/services/wms/outputformats.html

**Comment by JakobMiksch** [comment]
done with 307656237a0f370dc08deafc0a05ab126ebc2543
